### ISSUE TITLE
Doesn't build with clang-3.6 on Linux

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#228]
[199/408] Linking CXX executable cpu/hamaji/study
FAILED: : && /usr/bin/clang++   -O3 -std=c++11 -O3 -DNDEBUG   cpu/hamaji/CMakeFiles/study_hamaji.dir/study.cc.o  -o cpu/hamaji/study  -rdynamic cpu/hamaji/libhamaji_lib.a solver/libpuyoai_solver.a core/pattern/libpuyoai_core_pattern.a core/rensa/libpuyoai_core_rensa.a core/plan/libpuyoai_core_plan.a core/probability/libpuyoai_core_probability.a core/client/ai/libpuyoai_core_client_ai.a core/client/connector/libpuyoai_core_client_connector.a core/httpd/libpuyoai_core_httpd.a -lmicrohttpd core/rensa_tracker/libpuyoai_core_rensa_tracker.a core/libpuyoai_core.a base/libpuyoai_base.a -lpthread -lgflags -lglog && :
cpu/hamaji/libhamaji_lib.a(eval.cc.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/home/mayah/repos/puyoai.git/src/cpu/hamaji/eval.cc:(.text._ZN6google17MakeCheckOpStringIiiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x3a): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mayah** [comment]
Maybe hitting this?
https://llvm.org/bugs/show_bug.cgi?id=23529
